name: Docker CI

on:
  workflow_run:
    workflows: [ "Build CI" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: main
        required: true

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-ci.yaml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          branch: main
          event: push
          name: trojan-horse-artifact
          path: target/
          skip_unpack: true
          if_no_artifact_found: fail

      - name: Echo download path
        run: echo ${{steps.download-artifact.outputs.download-path}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPOSITORY }}:trojan-horse-latest
